sudo: false

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.11
  - DJANGO=master

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: DJANGO=1.11
    - python: "3.6"
      env: DJANGO=master
  exclude:
    - python: "3.4"
      env: DJANGO=master

install:
  - travis_retry pip install -U tox-travis

script:
  - tox

after_success:
  - travis_retry pip install -U codecov
  - codecov
